# Generated by Django 3.2.10 on 2022-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
